name: Replace String in Special Folder

on:
  push:
    branches:
      - develop  # Modify this according to your branch name
    paths:
      - 'docs/**/*.md'

jobs:
  replace_string:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Replace string
      if: steps.check_files.outputs.files_to_modify == 'true'
      run: |
        find ./docs -type f -name "*.md" -exec sed -i 's|/docs/public/images|/images|g' {} \;


    - name: Check Git status
      id: git_status
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "::set-output name=changes::true"
        else
          echo "::set-output name=changes::false"
        fi
      shell: bash

    - name: Commit changes
      if: steps.check_files.outputs.files_to_modify == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Replace old_string with new_string"
        git push